name: Burns AI Testing

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      
      - uses: education/autograding@v1
      
      #- name: Test with pytest
        # run: pytest   
        # run: pytest || [ $? = 1 ]     

      